GNUPG

diff --git a/legacy/bin/fish b/legacy/bin/fish
--- a/legacy/bin/fish
+++ b/legacy/bin/fish
@@ -7,28 +7,24 @@
 set -e
 
 # We can't call `fish` directly, because this wrapper needs to exist
-# before the *actual* fish binary in the path; however, since we know 
+# before the *actual* fish binary in the path; however, since we know
 # that ~/.profile has been sourced (see above), HOMEBREW_PREFIX is
 # available, and we can exec fish from there
 #
 # NOTE: We *cannot* use `exec` here, as doing so leads to weird  "OPTION
 #       ttyname=not a tty" errors with gpg-agent!
 #
-if [[ -n "$HOMEBREW_PREFIX" ]]; then
-	$HOMEBREW_PREFIX/bin/fish -l "$@"
+export OLD_PATH="$PATH"
+export PATH="$(echo ":$PATH:" | sed "s#:$HOME/bin:#:#g;s#:$HOME/local/bin:#:#g;s#:$HOME/.local/bin:#:#g;s#^:##;s#:\$##")"
+
+FISH_EXE="$(which fish 2>/dev/null)"
+
+export PATH="$OLD_PATH"
+unset OLD_PATH
+
+if [[ -n "$FISH_EXE" ]]; then
+    "$FISH_EXE" -l "$@"
 else
-	export OLD_PATH="$PATH"
-	export PATH="$(echo ":$PATH:" | sed "s#:$HOME/bin:#:#g;s#:$HOME/local/bin:#:#g;s#:$HOME/.local/bin:#:#g;s#^:##;s#:\$##")"
-
-	FISH_EXE="$(which fish 2> /dev/null)"
-
-	export PATH="$OLD_PATH"
-	unset OLD_PATH
-
-	if [[ -n "$FISH_EXE" ]]; then
-		"$FISH_EXE" -l "$@"
-	else
-		echo "Could not locate fish!"
-		exit 1
-	fi
+    echo "Could not locate fish!"
+    exit 1
 fi
